# Generated by Django 6.0.1 on 2026-03-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True),
        ),
    ]
