# Generated by Django 6.0.1 on 2026-02-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expiry_date',
            new_name='warranty_end_date',
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
