# Generated by Django 6.0.1 on 2026-02-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_expiry_date_product_warranty_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
