# Generated by Django 6.0.1 on 2026-02-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_product_documents_productdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='status',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.department'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vendor'),
        ),
    ]
