# Generated by Django 6.0.1 on 2026-02-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_unique_code_department_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
    ]
