# Generated by Django 6.0.1 on 2026-02-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_vendor_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
    ]
