# Generated by Django 6.0.1 on 2026-02-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_category_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlog',
            name='transfer_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
