# Generated by Django 6.0.1 on 2026-02-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_repairlog_updated_at_repairstatus_is_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
